version: "3.8"

services:
  server:
    build: .
    container_name: multimodallivekit-server-1
    command: python3 agent.py dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
